from sys import argv

colors: dict[str] = {
    "BLACK"        : "0",
    "BLUE"         : "1",
    "GREEN"        : "2",
    "CYAN"         : "3",
    "RED"          : "4",
    "PURPLE"       : "5",
    "BROWN"        : "6",
    "GRAY"         : "7",
    "DARK_GRAY"    : "8",
    "LIGHT_BLUE"   : "9",
    "LIGHT_GREEN"  : "a",
    "LIGHT_CYAN"   : "b",
    "LIGHT_RED"    : "c",
    "LIGHT_PURPLE" : "d",
    "YELLOW"       : "e",
    "WHITE"        : "f"
}

def generate():
    result: str = \
        "// This file was generated by\n" + \
        "// scripts/gencolours.py. DO NOT MODIFY.\n" + \
        "#pragma once\n" + \
        "#define INCLUDED_COLOR\n"
    for color in colors:
        result += "#define " + color + " 0x" + colors[color] + "\n"
    for bgcolor in colors:
        for fgcolor in colors:
            if bgcolor != fgcolor:
                bgcode: str = colors[bgcolor]
                fgcode: str = colors[fgcolor]
                result += f"#define {fgcolor}_ON_{bgcolor} 0x{bgcode}{fgcode}\n"
    return result

def fwrite(filename: str, data: str):
    with open(filename, "w") as f:
        return f.write(str(data))

if len(argv) > 1:
    fwrite(argv[1], generate())
